name: Release
on:
  push:
    tags:
      - 'v*.*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Fetch Tags
        run: git fetch --depth=1 origin +$GITHUB_REF:$GITHUB_REF

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build and Test the Plugin
        uses: ./.github/actions/gradle-build

      - name: Extract Changelog
        run: ./gradlew --console=plain --quiet getChangelog --no-header > ${{ runner.temp }}/release-changes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ runner.temp }}/release-changes.md
          files: dist/runtimesearch-plugin-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Plugin on JetBrains Marketplace
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin
